local M = {}
local W = require("utils.windows_ignore")

M.formatters_by_ft = {
	sh = { "beautysh" }, -- { "shfmt" },
	zsh = { "beautysh" }, -- { "shfmt" },
	c = { "clang_format" },
	cpp = { "clang_format" },
	objc = { "clang_format" },
	objcpp = { "clang_format" },
	cuda = { "clang_format" },
	proto = { "clang_format" },
	cmake = { "cmake_format" },
	html = { "prettier" },
	json = { "prettier" },
	xml = { "xmlformatter" },
	xsd = { "xmlformatter" },
	xsl = { "xmlformatter" },
	xslt = { "xmlformatter" },
	svg = { "xmlformatter" },
	bib = { "latexindent" },
	gitcommit = { "latexindent" },
	markdown = {},
	org = { "latexindent" },
	plaintex = { "latexindent" },
	rnoweb = { "latexindent" },
	tex = { "latexindent" },
	pandoc = { "latexindent" },
	quarto = { "latexindent" },
	rmd = { "latexindent" },
	rst = { "latexindent" },
	lua = { "stylua" },
	python = { "black" },
	yaml = { "prettier" },

	typescript = { "prettier" },
	javascriptreact = { "prettier" },
	typescriptreact = { "prettier" },
	svelte = { "prettier" },
	css = { "prettier" },
	graphql = { "prettier" },
}

M.linters_by_ft = {
	sh = { "shellcheck" },
	c = { "clangtidy" },
	cpp = { "clangtidy" },
	objc = { "clangtidy" },
	objcpp = { "clangtidy" },
	cuda = { "clangtidy" },
	proto = { "clangtidy" },
	cmake = { "cmakelint" },
	dockerfile = { "hadolint" },
	html = { "htmlhint" },
	json = { "jsonlint" },
	bib = {},
	gitcommit = {},
	markdown = {}, -- "write_good"
	org = {},
	plaintex = {},
	rnoweb = {},
	tex = {},
	pandoc = {},
	quarto = {},
	rmd = {},
	rst = {},
	lua = W.windows_ignore_dict({ "luacheck" }),
	python = { "flake8" },
	-- yaml = { "yamllint" },
}

return M
